---
title: "Aula 1"
output: html_notebook
---

# Preâmbulo
Este documento é um estudo que visa desenvolver uma metodologia para publicação de resultados de monitoramento ecológico.
Os objetivos é utilizar as tecnologias [R Markdown](http://rmarkdown.rstudio.com), para produção de conteúdo, e [GitHub](http://github.com/), para hospedagem e controle de versão (VCS) colaborativa.
A referência adotada pra implementação é o tutorial [Happy Git](https://happygitwithr.com/).

## Implementação do procedimento
Estamos trabalhando localmente com linux, onde foi implementado o sistema de segurança SSH.
Portanto a comunicação com servidor externo foi estabelecida através da porta, ou caminho, (SSH) do projeto no GitHub: ```git@github.com:DanDamb/aula1.git```

Para saber o local/caminho SSS use o comando```>git remote show origin``` no terminal.

Já está implementado o [Indice](https://dandamb.github.io/aula1/) e a [Aula 1](https://dandamb.github.io/aula1/Aula1.nb.html). Que por enquanto tem o mesmo conteúdo web.

[Aula 1](https://dandamb.github.io/aula1/Aula1.nb.html)

O procedimento de produção do material, no momento, é
1. gerar o conteúdo no em linguagem de marcação RMarkdown no RStudio e gerenciar o controle de verções com o Git.
Os comandos básicos no Git são os seguintes.

0) para sincronizar a pasta local com o projeto:
```
 git init
 git remote set-url origin git@github.com:DanDamb/aula1.git
```

1) para verificar o status dos arquivos do projeto:
```
git status
```


2) para verificar a localização remota dos arquivod do projeto
```
git remote -v
```
que no nosso caso resulta em:
```
  origin  git@github.com:DanDamb/aula1.git (fetch)
  origin  git@github.com:DanDamb/aula1.git (push)
```

3) para 'commitar' os arquivos locais no repositório GitHub:
```
 git commit -a -m "mensagem do commit"
 git push -u origin main
```

Este material está sendo produzido com tecnologia [R Markdown](http://rmarkdown.rstudio.com) 

Try executing this chunk by clicking the *Run* button within the chunk or by placing your cursor inside it and pressing *Ctrl+Shift+Enter*. 

```{r}
plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.
